#!/bin/bash

source `which veloxd`

if [ $# -lt 1 ]; then
  echo "Run as: $ velox-submit file"
  exit 1
fi

file_name="${1%.*}"
exec_cmd "g++ -c -std=c++14 -Wall -Werror -rdynamic -fpic $1"
exec_cmd "gcc -shared -fPIC -rdynamic -o ${file_name}.so ${file_name}.o"

app_dir=`velox_get_config "path.applications"`

velox_get_config "network.nodes" -v | xargs -L1 -P10 -IHOST scp ${file_name}.so HOST:$app_dir

echo "Submit"
