#!/bin/bash

source `which veloxd`

if [ $# -lt 1 ]; then
  echo "Run as: $ velox-submit file"
  exit 1
fi

file_name="${1%.*}"
exec_cmd "g++ -std=c++14 -Wall -Werror -o $file_name ${file_name}.cc -lvmr -lvdfs -lboost_system"
